"""Provenance: the header lines that say what produced a program.

A program found on the controller can be traced to its inputs from its
header alone. After ``Generated by`` (and ``Created``, unless the job
turns the timestamp off) come these lines, written whether or not comments
are, spelled exactly like this and in this order::

    ; source: DRAWING.svg sha256=HEX
    ; job-file: MACHINE.toml sha256=HEX
    ; job-file: none (command-line options)
    ; meta: KEY = VALUE
    ; versions: tcnc X, tangential-knife-cnc-geometry X, svgelements X, python X

``source`` and ``job-file`` give a file's name, never its directory, and
the SHA-256 of the bytes tcnc read. There is one ``job-file`` line per job
file in the order they were layered, or a single ``none`` line. ``meta``
lines are the job files' ``[meta]`` tables layered like ``[job]``: a later
file overrides a key, and a key keeps the position where it first
appeared. Nested tables flatten to dotted keys; values are written in TOML
form.

A line is written verbatim or not at all. A key, value or file name with a
control character, or a line longer than LinuxCNC reads, is an error: a
split or shortened provenance line would be ambiguous.
"""

import datetime as dt
import hashlib
import math
import platform
import re
from dataclasses import dataclass
from importlib.metadata import PackageNotFoundError, version
from typing import TYPE_CHECKING, Self, cast

from tcnc import __version__
from tcnc.errors import OptionError

if TYPE_CHECKING:
    from collections.abc import Mapping
    from pathlib import Path

MAX_LINE_BYTES = 252
"""Longest line LinuxCNC reads, in bytes without the newline.

The interpreter reads a line with ``fgets`` into a ``LINELEN`` (255) byte
buffer and rejects it as too long when 254 bytes, newline included, come back.
"""
COMPONENTS = ("tangential-knife-cnc-geometry", "svgelements")
"""The distributions besides tcnc whose version can change a program: the geometry kernel and the SVG parser."""
_BARE_KEY = re.compile(r"[A-Za-z0-9_-]+")
_CONTROL = re.compile(r"[\x00-\x1f\x7f]")


@dataclass(frozen=True, slots=True)
class FileDigest:
    """A file named by its base name and identified by the SHA-256 of its bytes."""

    name: str
    sha256: str

    @classmethod
    def of(cls, path: Path, data: bytes) -> Self:
        """The digest of ``data``, the bytes read from ``path``."""
        return cls(path.name, hashlib.sha256(data).hexdigest())

    @classmethod
    def read(cls, path: Path) -> Self:
        """Read ``path`` and digest its bytes.

        Raises:
            OptionError: When the file cannot be read.
        """
        try:
            data = path.read_bytes()
        except OSError as exc:
            msg = f"cannot read {path}: {exc}"
            raise OptionError(msg) from exc
        return cls.of(path, data)


@dataclass(frozen=True, slots=True)
class MetaEntry:
    """One ``[meta]`` entry: a dotted key and its value, both as TOML text."""

    key: str
    value: str


@dataclass(frozen=True, slots=True)
class ComponentVersion:
    """An installed component and its version."""

    name: str
    version: str


@dataclass(frozen=True, slots=True)
class Provenance:
    """What a program was made from; ``lines`` renders its header lines.

    ``from_options`` records that the job came from command-line options;
    it is only written when there are no ``job_files``.
    """

    source: FileDigest | None = None
    job_files: tuple[FileDigest, ...] = ()
    from_options: bool = False
    meta: tuple[MetaEntry, ...] = ()
    versions: tuple[ComponentVersion, ...] = ()

    def lines(self) -> tuple[str, ...]:
        """The header lines without the comment marker, in their documented order.

        Raises:
            OptionError: For a line that cannot be written verbatim.
        """
        lines: list[str] = []
        if self.source is not None:
            lines.append(f"source: {self.source.name} sha256={self.source.sha256}")
        if self.job_files:
            lines.extend(f"job-file: {digest.name} sha256={digest.sha256}" for digest in self.job_files)
        else:
            lines.append("job-file: none (command-line options)" if self.from_options else "job-file: none")
        lines.extend(f"meta: {entry.key} = {entry.value}" for entry in self.meta)
        if self.versions:
            lines.append("versions: " + ", ".join(f"{item.name} {item.version}" for item in self.versions))
        for line in lines:
            problem = line_problem(line)
            if problem is not None:
                msg = f"the header line {line!r} {problem}"
                raise OptionError(msg)
        return tuple(lines)


def line_problem(text: str) -> str | None:
    """Why ``text`` cannot be written as a header comment line as it stands, or ``None`` when it can."""
    if _CONTROL.search(text):
        return "contains a newline or control character"
    try:
        size = len(f"; {text}".encode())
    except UnicodeEncodeError:
        return "is not valid UTF-8"
    if size > MAX_LINE_BYTES:
        return f"would make a {size}-byte header line; LinuxCNC reads at most {MAX_LINE_BYTES} bytes per line"
    return None


def runtime_versions() -> tuple[ComponentVersion, ...]:
    """The installed versions of tcnc, the distributions in ``COMPONENTS`` and Python."""
    return (
        ComponentVersion("tcnc", __version__),
        *(ComponentVersion(name, _installed(name)) for name in COMPONENTS),
        ComponentVersion("python", platform.python_version()),
    )


def _installed(distribution: str) -> str:
    try:
        return version(distribution)
    except PackageNotFoundError:
        return "unknown"


def meta_entries(table: Mapping[str, object], *, where: str) -> tuple[MetaEntry, ...]:
    """A ``[meta]`` table flattened to dotted keys with TOML values, in table order.

    Nested tables become dotted keys; an empty one is written as ``{}``.
    Arrays, and tables inside arrays, stay inline. ``where`` names the file
    in errors.

    Raises:
        OptionError: For a key or value with a newline or control character,
            or an entry whose header line LinuxCNC could not read.
    """
    entries: list[MetaEntry] = []
    _flatten(table, (), entries, where)
    return tuple(entries)


def _flatten(table: Mapping[str, object], prefix: tuple[str, ...], entries: list[MetaEntry], where: str) -> None:
    for key, value in table.items():
        path = (*prefix, key)
        if isinstance(value, dict) and value:
            _flatten(cast("dict[str, object]", value), path, entries, where)
            continue
        entry = MetaEntry(".".join(_toml_key(part) for part in path), _toml_value(value))
        problem = line_problem(f"meta: {entry.key} = {entry.value}")
        if problem is not None:
            msg = f"{where}: [meta] {'.'.join(path)!r} {problem}"
            raise OptionError(msg)
        entries.append(entry)


def _toml_key(key: str) -> str:
    return key if _BARE_KEY.fullmatch(key) else _toml_string(key)


def _toml_string(text: str) -> str:
    # Control characters are left in on purpose: line_problem rejects them rather than escaping them.
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _toml_value(value: object) -> str:
    """``value`` as TOML writes it; arrays and tables inline."""
    match value:
        case list():
            return "[" + ", ".join(_toml_value(item) for item in cast("list[object]", value)) + "]"
        case dict():
            items = cast("dict[str, object]", value)
            return "{" + ", ".join(f"{_toml_key(key)} = {_toml_value(item)}" for key, item in items.items()) + "}"
        case _:
            return _toml_scalar(value)


def _toml_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float) and not math.isfinite(value):
        return "nan" if math.isnan(value) else ("inf" if value > 0.0 else "-inf")
    if isinstance(value, int | float):
        return repr(value)
    if isinstance(value, str):
        return _toml_string(value)
    if isinstance(value, dt.date | dt.time):  # a datetime is a date
        return value.isoformat()
    msg = f"not a TOML value: {value!r}"
    raise TypeError(msg)
