"""Golden G-code files: the CLI pipeline end to end, byte for byte.

The header names the installed versions; these tests pin them to
``GOLDEN_VERSION`` so neither a release nor a dependency update changes
every golden. The ``source:`` and ``job-file:`` lines hash the fixture
files, so editing a fixture changes its goldens. Regenerate
deliberately with ``TCNC_UPDATE_GOLDEN=1 uv run pytest tests/test_golden.py``
and review the diff before committing.
"""

import math
import os
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from tcnc.cli import run
from tcnc.jobfile import load_job_files
from tcnc.options import KnifeOptions
from tcnc.provenance import COMPONENTS, ComponentVersion

if TYPE_CHECKING:
    from collections.abc import Callable

GOLDEN_DIR = Path(__file__).parent / "golden"
FIXED_NOW = datetime(2026, 9, 12, 12, 0, tzinfo=UTC)
GOLDEN_VERSION = "0.0.0"
GOLDEN_VERSIONS = tuple(ComponentVersion(name, GOLDEN_VERSION) for name in ("tcnc", *COMPONENTS, "python"))


@pytest.fixture(autouse=True)
def _pinned_versions(monkeypatch: pytest.MonkeyPatch) -> None:
    """Hold the ``Generated by`` and ``versions:`` lines still: the writer's version and the run's components."""
    monkeypatch.setattr("tcnc.gcode.__version__", GOLDEN_VERSION)
    monkeypatch.setattr("tcnc.cli.runtime_versions", lambda: GOLDEN_VERSIONS)


# The fixture pages are 4 in (101.6 mm) square; the option values below are millimetres.
CASES: dict[str, tuple[str, KnifeOptions]] = {
    "square": ("square.svg", KnifeOptions(corner_angle=math.radians(15), overcut=1.0, z_depth=-1.5)),
    "circle": ("circle.svg", KnifeOptions(overcut=2.5)),
    "rounded-rect": ("rounded-rect.svg", KnifeOptions(overcut=1.0)),
    "star": ("star.svg", KnifeOptions(overcut=1.0)),
    "polyline-open": ("polyline-open.svg", KnifeOptions(corner_angle=math.radians(15), overcut=1.0)),
    "quadratic": ("quadratic.svg", KnifeOptions(overcut=1.0)),
    "mm-document": ("mm-document.svg", KnifeOptions(overcut=1.0, z_depth=-1.5, z_safe=5.0)),
    "multipass": ("square.svg", KnifeOptions(z_depth=-5.0, z_step=2.5, overcut=1.0)),
    "nearest": ("elliptical-arc.svg", KnifeOptions(sort_method="nearest", overcut=1.0)),
    "blade-offset": ("rounded-rect.svg", KnifeOptions(blade_offset=1.0, overcut=1.0)),
    "oscillation-cut": (
        "square.svg",
        KnifeOptions(oscillation_mode="cut", spindle_speed=1000, spindle_wait_on=0.5, overcut=1.0),
    ),
    "oscillation-off": ("circle.svg", KnifeOptions(oscillation_mode="off")),
    "layer-filter": ("layers.svg", KnifeOptions(layers=("Cuts",), overcut=1.0)),
    "numbered-with-settings": ("square.svg", KnifeOptions(gcode_line_numbers=True, write_settings=True, overcut=1.0)),
    "a-offset-exact": ("star.svg", KnifeOptions(a_offset=math.radians(90), blend_mode="exact", overcut=1.0)),
    "blade-offset-square": ("square.svg", KnifeOptions(blade_offset=1.0, overcut=1.0, corner_angle=math.radians(15))),
    "blade-offset-circle-overcut": ("circle.svg", KnifeOptions(blade_offset=5.0, overcut=5.0)),
    "hairpin-offset": (
        "polyline-open.svg",
        KnifeOptions(blade_offset=1.0, overcut=0.5, corner_angle=math.radians(120)),
    ),
}


# Multi-tool jobs: the job files to layer; the first names the drawing.
JOB_CASES: dict[str, tuple[str, ...]] = {
    "box-job": ("box.toml",),
    "box-job-change-height": ("box.toml", "tool-change-z.toml"),
}


@pytest.mark.parametrize("name", sorted(CASES) + sorted(JOB_CASES))
def test_golden(name: str, fixture: Callable[[str], Path], tmp_path: Path) -> None:
    out = tmp_path / f"{name}.ngc"
    if name in JOB_CASES:
        loaded = load_job_files([fixture(job_file) for job_file in JOB_CASES[name]])
        assert loaded.input is not None
        run(loaded.job, loaded.input, out, job_file=loaded, now=lambda: FIXED_NOW)
    else:
        svg_name, options = CASES[name]
        run(options, fixture(svg_name), out, now=lambda: FIXED_NOW)
    produced = out.read_text()
    golden = GOLDEN_DIR / f"{name}.ngc"
    if os.environ.get("TCNC_UPDATE_GOLDEN"):
        golden.write_text(produced)
    assert golden.is_file(), f"missing golden {golden.name}; run with TCNC_UPDATE_GOLDEN=1"
    assert produced == golden.read_text()
