"""Command line end to end."""

import hashlib
import platform
from dataclasses import fields
from importlib.metadata import version
from pathlib import Path
from typing import TYPE_CHECKING

import pytest
from geom2d import P

from tcnc import __version__
from tcnc.cli import (
    EXIT_OK,
    EXIT_PLAN,
    EXIT_SVG,
    EXIT_USAGE,
    KNIFE_OPTIONS,
    build_parser,
    main,
    options_from_namespace,
    run,
)
from tcnc.errors import OptionError
from tcnc.options import KnifeOptions

if TYPE_CHECKING:
    from collections.abc import Callable


def test_parser_defaults_match_options() -> None:
    ns = build_parser().parse_args(["in.svg"])
    assert options_from_namespace(ns) == KnifeOptions()
    ns = build_parser().parse_args(["in.svg", "--corner-angle", "30", "--id", "a", "--id", "b"])
    opts = options_from_namespace(ns)
    assert opts.corner_angle == pytest.approx(0.5235987755982988)
    assert opts.ids == ("a", "b")
    # Every option field is set by the parser and nothing else pretends to be one.
    dests = {action.dest for action in build_parser()._actions}
    assert {field.name for field in fields(KnifeOptions)} <= dests


def test_every_knife_option_is_listed_for_the_job_file_check() -> None:
    parser = build_parser()
    listed = {
        option
        for action in parser._actions
        for option in action.option_strings
        if action.dest not in ("help", "version", "debug", "output", "preview", "jobs", "only", "skip", "timestamp")
    }
    assert listed == set(KNIFE_OPTIONS)


def test_square_end_to_end(fixture: Callable[[str], Path], tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    out = tmp_path / "square.ngc"
    preview = tmp_path / "square-preview.svg"
    code = main(
        [
            str(fixture("square.svg")),
            "-o",
            str(out),
            "--preview",
            str(preview),
            "--corner-angle",
            "15",
            "--overcut",
            "0.05",
        ]
    )
    assert code == EXIT_OK
    text = out.read_text()
    assert text.startswith("%\n")
    assert "M2" in text
    assert text.count("G1 Z-1.000") == 4
    assert preview.read_text().startswith("<svg ")
    captured = capsys.readouterr()
    assert "4 cuts" in captured.out
    assert not list(tmp_path.glob(".*.tmp"))


def test_skipped_content_is_listed_on_stderr(
    fixture: Callable[[str], Path], tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main([str(fixture("layers.svg")), "-o", str(tmp_path / "layers.ngc"), "--layer", "Cuts"]) == EXIT_OK
    captured = capsys.readouterr()
    assert "1 cut," in captured.out
    assert captured.err.splitlines() == [
        "tcnc: skipped: layer Marks: 1 path not selected by any operation",
        "tcnc: skipped: layer Cuts: 2 paths hidden",
        "tcnc: skipped: layer Guides: 1 path hidden",
    ]
    assert main([str(fixture("square.svg")), "-o", str(tmp_path / "square.ngc")]) == EXIT_OK
    assert capsys.readouterr().err == ""  # nothing in the drawing was left out


def header(text: str) -> list[str]:
    """The comment lines between the opening ``%`` and the first command or blank line."""
    lines: list[str] = []
    for line in text.splitlines()[1:]:
        if not line.startswith(";"):
            break
        lines.append(line)
    return lines


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def copy_box(fixture: Callable[[str], Path], tmp_path: Path) -> tuple[Path, Path]:
    """The box drawing and its job file, copied so a test may change them."""
    drawing, machine = tmp_path / "box.svg", tmp_path / "box.toml"
    drawing.write_bytes(fixture("box.svg").read_bytes())
    machine.write_bytes(fixture("box.toml").read_bytes())
    return drawing, machine


def test_header_names_the_drawing_the_job_files_their_meta_and_the_versions(
    fixture: Callable[[str], Path], tmp_path: Path
) -> None:
    drawing, machine = copy_box(fixture, tmp_path)
    layout = tmp_path / "layout.toml"
    layout.write_text('[meta]\nproducer = "layout generator"\nsheet = "A"\n\n[meta.drawing]\nrevision = 7\n')
    out = tmp_path / "box.ngc"
    assert main(["--job", str(machine), "--job", str(layout), "-o", str(out)]) == EXIT_OK
    lines = header(out.read_text())
    assert lines[0] == f"; Generated by tcnc {__version__}"
    assert lines[1].startswith("; Created ")
    assert lines[2:10] == [
        f"; source: box.svg sha256={sha256(drawing)}",
        f"; job-file: box.toml sha256={sha256(machine)}",
        f"; job-file: layout.toml sha256={sha256(layout)}",
        '; meta: producer = "layout generator"',  # the later file wins; the key keeps its first position
        '; meta: drawing.name = "box"',
        "; meta: drawing.revision = 7",
        '; meta: sheet = "A"',
        (
            f"; versions: tcnc {__version__}, tangential-knife-cnc-geometry {version('tangential-knife-cnc-geometry')}, "
            f"svgelements {version('svgelements')}, python {platform.python_version()}"
        ),
    ]
    assert lines[10] == "; Units: mm; A axis unwrapped; material surface at Z0"


@pytest.mark.parametrize("name", ["square.svg", "mm-document.svg"])
def test_source_hash_is_the_file_as_it_is_on_disk(name: str, fixture: Callable[[str], Path], tmp_path: Path) -> None:
    # The loader rewrites an inch or mm root size before parsing; the hash is of the bytes before that.
    out = tmp_path / "out.ngc"
    assert main([str(fixture(name)), "-o", str(out)]) == EXIT_OK
    lines = header(out.read_text())
    assert f"; source: {name} sha256={sha256(fixture(name))}" in lines
    assert "; job-file: none (command-line options)" in lines


def test_identity_lines_are_written_without_comments(fixture: Callable[[str], Path], tmp_path: Path) -> None:
    out = tmp_path / "quiet.ngc"
    assert main([str(fixture("square.svg")), "-o", str(out), "--no-gcode-comments", "--write-settings"]) == EXIT_OK
    comments = [line for line in out.read_text().splitlines() if ";" in line]
    assert [line.split(" ", 2)[1] for line in comments] == ["Generated", "source:", "job-file:", "versions:"]
    assert header(out.read_text()) == comments  # all of them at the top, nothing else commented


def test_no_timestamp_gives_byte_identical_programs(fixture: Callable[[str], Path], tmp_path: Path) -> None:
    drawing, machine = copy_box(fixture, tmp_path)
    first, second = tmp_path / "first.ngc", tmp_path / "second.ngc"
    for out in (first, second):
        assert main(["--job", str(machine), "-o", str(out), "--no-timestamp"]) == EXIT_OK
    assert first.read_bytes() == second.read_bytes()
    assert "Created" not in first.read_text()

    def changed_lines() -> list[str]:
        assert main(["--job", str(machine), "-o", str(second), "--no-timestamp"]) == EXIT_OK
        pairs = zip(first.read_text().splitlines(), second.read_text().splitlines(), strict=True)
        return [after.split(" sha256=")[0] for before, after in pairs if before != after]

    drawing.write_bytes(drawing.read_bytes() + b" ")
    assert changed_lines() == ["; source: box.svg"]
    first.write_bytes(second.read_bytes())
    machine.write_bytes(machine.read_bytes() + b"\n")
    assert changed_lines() == ["; job-file: box.toml"]


def test_timestamp_setting_and_source_date_epoch(
    fixture: Callable[[str], Path], tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    _, machine = copy_box(fixture, tmp_path)
    quiet = tmp_path / "quiet.toml"
    quiet.write_text("[job]\ntimestamp = false\n")
    out = tmp_path / "box.ngc"
    assert main(["--job", str(machine), "--job", str(quiet), "-o", str(out)]) == EXIT_OK
    assert not any(line.startswith("; Created") for line in header(out.read_text()))
    monkeypatch.setenv("SOURCE_DATE_EPOCH", "86400")
    assert main(["--job", str(machine), "--job", str(quiet), "-o", str(out), "--timestamp"]) == EXIT_OK
    assert header(out.read_text())[1] == "; Created 1970-01-02T00:00:00+00:00"
    monkeypatch.setenv("SOURCE_DATE_EPOCH", "tomorrow")
    assert main(["--job", str(machine), "-o", str(out)]) == EXIT_USAGE
    assert "SOURCE_DATE_EPOCH" in capsys.readouterr().err


def test_meta_that_cannot_be_written_is_a_usage_error(
    fixture: Callable[[str], Path], tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    _, machine = copy_box(fixture, tmp_path)
    layout = tmp_path / "layout.toml"
    out = tmp_path / "box.ngc"
    layout.write_text('[meta]\nmesh_revision = "af34\\nb"\n')
    assert main(["--job", str(machine), "--job", str(layout), "-o", str(out)]) == EXIT_USAGE
    err = capsys.readouterr().err
    assert f"job file {layout}: [meta] 'mesh_revision' contains a newline or control character" in err
    layout.write_text(f'[meta]\nnotes = "{"x" * 300}"\n')
    assert main(["--job", str(machine), "--job", str(layout), "-o", str(out)]) == EXIT_USAGE
    assert "LinuxCNC reads at most 252 bytes per line" in capsys.readouterr().err
    assert not out.exists()


def test_default_output_name(fixture: Callable[[str], Path], tmp_path: Path) -> None:
    src = tmp_path / "copy.svg"
    src.write_bytes(fixture("circle.svg").read_bytes())
    assert main([str(src)]) == EXIT_OK
    assert (tmp_path / "copy.ngc").exists()


def test_error_exit_codes(fixture: Callable[[str], Path], tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    out = str(tmp_path / "x.ngc")
    assert main([str(tmp_path / "missing.svg"), "-o", out]) == EXIT_SVG
    assert "not found" in capsys.readouterr().err
    assert main([str(fixture("layers.svg")), "-o", out, "--layer", "Nothing"]) == EXIT_SVG
    assert "no cuttable geometry" in capsys.readouterr().err
    assert main([str(fixture("square.svg")), "-o", out, "--tolerance", "0"]) == EXIT_USAGE
    assert "tolerance" in capsys.readouterr().err
    with pytest.raises(SystemExit) as info:
        main([str(fixture("square.svg")), "--blend-mode", "furlongs"])
    assert info.value.code == EXIT_USAGE
    assert not Path(out).exists()


def test_output_write_error_uses_documented_exit_code(
    fixture: Callable[[str], Path], tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main([str(fixture("square.svg")), "-o", str(tmp_path / "absent" / "out.ngc")]) == EXIT_PLAN
    assert "cannot write output" in capsys.readouterr().err
    assert main([str(fixture("square.svg")), "-o", str(tmp_path / "x.ngc"), "--z-safe", "-1"]) == EXIT_USAGE


def test_failed_preview_leaves_the_previous_program_in_place(
    fixture: Callable[[str], Path], tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    output = tmp_path / "out.ngc"
    output.write_text("OLD PROGRAM")
    preview = tmp_path / "preview-dir"
    preview.mkdir()
    assert main([str(fixture("square.svg")), "-o", str(output), "--preview", str(preview)]) == EXIT_PLAN
    assert "is a directory" in capsys.readouterr().err
    assert output.read_text() == "OLD PROGRAM"
    assert not list(tmp_path.glob(".*"))


def test_runs_of_short_links_are_cut_not_rejected(tmp_path: Path) -> None:
    for data in (
        "M0 0 L96 0 L96.00001 0 L96.00002 0 L96.00003 0 L192 0",
        "M0 0 L96 0 L96 96 L0 0.00001 L0 0.00002 Z",
    ):
        path = tmp_path / "links.svg"
        path.write_text(f'<svg xmlns="http://www.w3.org/2000/svg" width="384" height="384"><path d="{data}"/></svg>')
        assert main([str(path), "-o", str(tmp_path / "links.ngc")]) == EXIT_OK


def test_awkward_geometry_reaches_the_documented_exit_codes(tmp_path: Path) -> None:
    # An arc whose end rounds onto its centre at three decimals (allowed by a 1e-7 tolerance).
    radius = 0.00051001
    p1, p2 = P.from_polar(radius, 0.1), P.from_polar(radius, 0.4)
    arc = tmp_path / "arc.svg"
    arc.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" width="1mm" height="1mm" viewBox="0 0 1 1">'
        f'<path d="M{p1.x!r} {p1.y!r} A{radius!r} {radius!r} 0 0 1 {p2.x!r} {p2.y!r}"/></svg>'
    )
    assert main([str(arc), "-o", str(tmp_path / "arc.ngc"), "--tolerance", "1e-7"]) in (EXIT_OK, EXIT_PLAN)
    # A thin ellipse is cut, not rejected during curve fitting.
    thin = tmp_path / "thin.svg"
    thin.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" width="384" height="384">'
        '<path d="M96 96 A100 0.000001 0 1 1 106 96"/></svg>'
    )
    assert main([str(thin), "-o", str(tmp_path / "thin.ngc")]) == EXIT_OK
    assert (
        main([str(thin), "-o", str(tmp_path / "thin-offset.ngc"), "--blade-offset", "1", "--overcut", "1"]) == EXIT_OK
    )


def test_output_and_preview_must_be_distinct(fixture: Callable[[str], Path], tmp_path: Path) -> None:
    output = tmp_path / "out.ngc"
    with pytest.raises(OptionError):
        run(KnifeOptions(), fixture("square.svg"), output, output)
    with pytest.raises(OptionError):
        run(KnifeOptions(), fixture("square.svg"), fixture("square.svg"))
    assert not output.exists()


def test_version(capsys: pytest.CaptureFixture[str]) -> None:
    with pytest.raises(SystemExit) as info:
        main(["--version"])
    assert info.value.code == 0
    assert capsys.readouterr().out.startswith("tcnc ")
